weather_discriptions_to_emojis = {
    """thunderstorm with light rain""": """:thunder_cloud_rain:""",
    """thunderstorm with rain""": """:thunder_cloud_rain:""",
    """thunderstorm with heavy rain""": """:thunder_cloud_rain:""",
    """thunderstorm with light drizzle""": """:thunder_cloud_rain:""",
    """thunderstorm with drizzle""": """:thunder_cloud_rain:""",
    """thunderstorm with heavy drizzle""": """:thunder_cloud_rain:""",
    """light thunderstorm""": """:cloud_lightning:""",
    """thunderstorm""": """:cloud_lightning:""",
    """heavy thunderstorm""": """:cloud_lightning:""",
    """ragged thunderstorm""": """:cloud_lightning:""",
    """light intensity drizzle""": """:cloud_rain:""",
    """drizzle""": """:cloud_rain:""",
    """heavy intensity drizzle""": """:cloud_rain:""",
    """light intensity drizzle rain""": """:cloud_rain:""",
    """drizzle rain""": """:cloud_rain:""",
    """heavy intensity drizzle rain""": """:cloud_rain:""",
    """shower rain and drizzle""": """:cloud_rain:""",
    """heavy shower rain and drizzle""": """:cloud_rain:""",
    """shower drizzle""": """:cloud_rain:""",
    """light rain""": """:cloud_rain:""",
    """moderate rain""": """:cloud_rain:""",
    """heavy intensity rain""": """:cloud_rain:""",
    """very heavy rain""": """:cloud_rain:""",
    """extreme rain""": """:cloud_rain:""",
    """freezing rain""": """:cloud_rain:""",
    """light intensity shower rain""": """:cloud_rain:""",
    """shower rain""": """:cloud_rain:""",
    """heavy intensity shower rain""": """:cloud_rain:""",
    """ragged shower rain""": """:cloud_rain:""",
    """light snow""": """:cloud_snow:""",
    """Snow""": """:cloud_snow:""",
    """Heavy snow""": """:cloud_snow:""",
    """Sleet""": """:cloud_snow:""",
    """Light shower sleet""": """:cloud_snow:""",
    """Shower sleet""": """:cloud_snow:""",
    """Light rain and snow""": """:cloud_snow:""",
    """Rain and snow""": """:cloud_snow:""",
    """Light shower snow""": """:cloud_snow:""",
    """Shower snow""": """:cloud_snow:""",
    """Heavy shower snow""": """:cloud_snow:""",
    """mist""": """:fog:""",
    """Smoke""": """:fog:""",
    """Haze""": """:fog:""",
    """fog""": """:fog:""",
    """sand/ dust whirls""": """:cloud_tornado:""",
    """sand""": """:fog:""",
    """dust""": """:fog:""",
    """volcaic ash""": """:volcano:""",
    """squalls""": """:dash:""",
    """tornado""": """:cloud_tornado:""",
    """clear sky""": """:sunny:""",
    """few clouds""": """:white_sun_small_cloud:""",
    """scattered clouds""": """:partly_sunny:""",
    """	broken clouds""": """:white_sun_cloud:""",
    """	overcast clouds""": """:cloud:""",
}
